spring:
  application:
    name: gateway
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        register-health-check: true
    gateway:
      routes:
        - id: user
#          uri: http://localhost:9999/
          uri: lb://user     #通过注册的服务名来获取请求uri    lb代表转发后台服务实现负载均衡
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar

        - id: product
#          uri: http://localhost:9998/
          uri: lb://product
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      discovery:
        locator:
          enabled: true    #开启根据服务名动态获取路由
          lowerCaseServiceId: true
