spring:
  application:
    name: user
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register-health-check: true
feign:
  hystrix:
    enabled: true    #开启feign对hystrix的支持
